### ISSUE TITLE
Add correct i18n setting for Special Page list to show

### ISSUE THREAD

**Issue by frankduncan** [OpenTechStrategies/PickSome#1]
Currently, when you go to Special:SpecialPages on a wiki with PickSome installed, under other special pages it lists "⧼picksome⧽".  That should come from the i18n files, and should reuse "picksome-title" if possible.

I know https://github.com/OpenTechStrategies/SimpleFavorites does it correctly.

**Comment by YaxelPerez** [comment]
working on this today (fri, jun 12)

**Comment by kfogel** [comment]
On phone with @YaxelPerez right now; still working on this.

**Comment by kfogel** [comment]
Closing now, after confirming on phone with @YaxelPerez that this is all done and that the updated commit is on mainline.
